# 登录的数据
# 1、正常场景：用户名、密码正确，登录成功
- logindata: {"account":"mazhenhua8@zdsztech.com","password":"dog7jCEMgBCy02XUcrsv4w==","language":"CN"}  # 登录的用户
  exp: {"code": "200", "message": "操作成功!" ,"datatotal": 0 ,"getActivityLog": 39}   # 登录的预期结果
  # 1 我的项目的数量
  listAllProjectByCondition: {"page":1,"pageSize":16,"projectName":null,"dropDownType":null,"dropDownId":null,"dataType":1}
  #获取用户列表
  getActivityLogByCreateId: {"projectId":1250453976294670336,"page":1,"pageSize":20,"isProjectOverviewLog":false,"isCompanyLog":false,"isProjectLog":true}
#  查看公司下的成员
  listCompanyUserPage: {}
  changeCompanyLogin: {"companyId":"1071440842016989184"}
  listProjectByCondition:   {"page":1,"pageSize":9,"projectName":null,"dataType": 1 ,"dropDownId": "1242878101646774272" }
# 归档项目
  updateProjectDataType: {}
#  将项目从回收站里恢复
  recoverProject: {}
#  添加项目成员
  changeProjectResourc: {}
#  移除项目成员
  deleteProjectResource: {}
#  创建项目模板
  copeProjectByProjectId: {}
#  删除项目模板
  deletecopyProject: {}
#  复制项目模板
  copyProjectTemplate: {}
  updateProjectAPPByProjectId: {"projectAppStatus": 0, "projectId": "1245765721859072000", "projectAppId": "1245765723448713216", "projectAppName": "项目概览"}
#  添加项目
  addProject: {"projectResource": [], "projectName": "pythontest", "scope": 1, "projectManager": "955422446754861056", "projectRecommend": "你好", "backType": 1, "countryRegionId": "860892363952885760"}
#  添加任务
  addTask: {}
  changeProjectPahse: {phaseId: "-1", projectId: "1246134768836583424"}
#  获取relId和查看当前项目下所有的成员
  getUserIdsByProjectId: {}
# 查看所有项目
  getProjectLis: {}
#  查看项目下部门
  listDept: {}
#- logindata: {"account":"mazhenhua8@zdsztech.com","password":"dog7jCEMgBCy02XUcrsv4w==","language":"CN"}  # 登录的用户
#  exp: {"code": "200", "message": "操作成功!" ,"datatotal": 18 ,"getActivityLog": 39}   # 登录的预期结果
#  # 2 XXX
#  listAllProjectByCondition: { "page": 1,"pageSize": 16,"projectName": null,"dropDownType": null,"dropDownId": null,"dataType": 2 }
#  getActivityLogByCreateId: {"page":1,"pageSize":20,"isProjectOverviewLog":false,"isCompanyLog":false,"isProjectLog":true}
#  changeCompanyLogin: {"companyId":"1071440842016989184"}
#  listProjectByCondition:   {"page":1,"pageSize":9,"projectName":null,"dataType":1}
#  deleteProject: {"projectIds": ["1103995636598071297"]}
#
#- logindata: {"account":"mazhenhua8@zdsztech.com","password":"dog7jCEMgBCy02XUcrsv4w==","language":"CN"}  # 登录的用户
#  exp: {"code": "200", "message": "操作成功!" ,"datatotal": 1 ,"getActivityLog": 39}   # 登录的预期结果
#  # 3 我的已归档数量
#  listAllProjectByCondition: { "page": 1,"pageSize": 16,"projectName": null,"dropDownType": null,"dropDownId": null,"dataType": 3 }
#  getActivityLogByCreateId: {"page":1,"pageSize":20,"isProjectOverviewLog":false,"isCompanyLog":false,"isProjectLog":true}
#  changeCompanyLogin: {"companyId":"1071440842016989184"}
#  listProjectByCondition:  {"page":1,"pageSize":9,"projectName":null,"dataType":1}
#  deleteProject: {"projectIds": ["1103995636598071297"]}
#
#- logindata: {"account":"mazhenhua8@zdsztech.com","password":"dog7jCEMgBCy02XUcrsv4w==","language":"CN"}  # 登录的用户
#  exp: {"code": "200", "message": "操作成功!" ,"datatotal": 5 ,"getActivityLog": 39}   # 登录的预期结果
#  # 4 项目模版 数量
#  listAllProjectByCondition: { "page": 1,"pageSize": 16,"projectName": null,"dropDownType": null,"dropDownId": null,"dataType": 4 }
#  getActivityLogByCreateId: {"page":1,"pageSize":20,"isProjectOverviewLog":false,"isCompanyLog":false,"isProjectLog":true}
#  changeCompanyLogin: {"companyId":"1071440842016989184"}
#  listProjectByCondition:   {"page":1,"pageSize":9,"projectName":null,"dataType":1}
#  deleteProject: {"projectIds": ["1103995636598071297"]}
